AllCops:
  Exclude:
    - './bin/**/*'
require:
  - rubocop-rails
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
